/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Rafael Gorayb
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setResizable(false);

        URL url = this.getClass().getResource("Logo.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botaoCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        medianaLabel4 = new javax.swing.JLabel();
        coeficienteDeVariacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medianaLabel2 = new javax.swing.JLabel();
        variancia = new javax.swing.JTextField();
        medianaLabel3 = new javax.swing.JLabel();
        desvioPadrao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        medianaLabel = new javax.swing.JLabel();
        mediana = new javax.swing.JTextField();
        medianaLabel1 = new javax.swing.JLabel();
        moda = new javax.swing.JTextField();
        mediaLabel = new javax.swing.JLabel();
        media = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelArquivo = new javax.swing.JLabel();
        arquivoLoc = new javax.swing.JTextField();
        addValor = new javax.swing.JTextField();
        adicionarAmostra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        removerLinha = new javax.swing.JButton();
        apagarTudo = new javax.swing.JButton();
        amostraTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        delimitador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        colunaDesejada = new javax.swing.JTextField();
        botaoResultados = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA+ Calculadora Estatística");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        jButton1.setText("Selecionar Arquivo");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(true);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoCalcular.setBackground(new java.awt.Color(51, 51, 51));
        botaoCalcular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCalcular.setForeground(new java.awt.Color(204, 204, 204));
        botaoCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        botaoCalcular.setText("Calcular");
        botaoCalcular.setContentAreaFilled(false);
        botaoCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        botaoCalcular.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        medianaLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        medianaLabel4.setForeground(new java.awt.Color(51, 51, 51));
        medianaLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medianaLabel4.setText("Coef. de Variação:");

        coeficienteDeVariacao.setEditable(false);
        coeficienteDeVariacao.setBackground(new java.awt.Color(204, 204, 204));
        coeficienteDeVariacao.setForeground(new java.awt.Color(51, 51, 51));
        coeficienteDeVariacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coeficienteDeVariacao.setBorder(null);
        coeficienteDeVariacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteDeVariacaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Medidas de dispersão");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        medianaLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        medianaLabel2.setForeground(new java.awt.Color(51, 51, 51));
        medianaLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medianaLabel2.setText("Variância:");

        variancia.setEditable(false);
        variancia.setBackground(new java.awt.Color(204, 204, 204));
        variancia.setForeground(new java.awt.Color(51, 51, 51));
        variancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        variancia.setBorder(null);
        variancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianciaActionPerformed(evt);
            }
        });

        medianaLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        medianaLabel3.setForeground(new java.awt.Color(51, 51, 51));
        medianaLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medianaLabel3.setText("Desvio Padrão:");

        desvioPadrao.setEditable(false);
        desvioPadrao.setBackground(new java.awt.Color(204, 204, 204));
        desvioPadrao.setForeground(new java.awt.Color(51, 51, 51));
        desvioPadrao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        desvioPadrao.setBorder(null);
        desvioPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desvioPadraoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Medidas de tendência central");

        medianaLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        medianaLabel.setForeground(new java.awt.Color(51, 51, 51));
        medianaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medianaLabel.setText("Mediana:");

        mediana.setEditable(false);
        mediana.setBackground(new java.awt.Color(204, 204, 204));
        mediana.setForeground(new java.awt.Color(51, 51, 51));
        mediana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mediana.setBorder(null);
        mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianaActionPerformed(evt);
            }
        });

        medianaLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        medianaLabel1.setForeground(new java.awt.Color(51, 51, 51));
        medianaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medianaLabel1.setText("Moda:");

        moda.setEditable(false);
        moda.setBackground(new java.awt.Color(204, 204, 204));
        moda.setForeground(new java.awt.Color(51, 51, 51));
        moda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        moda.setBorder(null);
        moda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modaActionPerformed(evt);
            }
        });

        mediaLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mediaLabel.setForeground(new java.awt.Color(51, 51, 51));
        mediaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediaLabel.setText("Média:");

        media.setEditable(false);
        media.setBackground(new java.awt.Color(204, 204, 204));
        media.setForeground(new java.awt.Color(51, 51, 51));
        media.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        media.setBorder(null);
        media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel6.setEnabled(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mediaLabel)
                        .addGap(52, 52, 52)
                        .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medianaLabel)
                            .addComponent(medianaLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mediana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(medianaLabel3)
                                .addGap(45, 45, 45))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medianaLabel4)
                                    .addComponent(medianaLabel2))
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coeficienteDeVariacao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(variancia)
                            .addComponent(desvioPadrao)))
                    .addComponent(jLabel3))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medianaLabel3)
                            .addComponent(desvioPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medianaLabel2)
                            .addComponent(variancia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medianaLabel4)
                            .addComponent(coeficienteDeVariacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mediaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mediana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medianaLabel))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medianaLabel1)
                            .addComponent(moda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        labelArquivo.setBackground(new java.awt.Color(153, 153, 153));
        labelArquivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelArquivo.setForeground(new java.awt.Color(51, 51, 51));
        labelArquivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelArquivo.setText("Arquivo:");
        labelArquivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        arquivoLoc.setEditable(false);
        arquivoLoc.setBackground(new java.awt.Color(234, 236, 236));
        arquivoLoc.setForeground(new java.awt.Color(51, 51, 51));
        arquivoLoc.setBorder(null);

        addValor.setBackground(new java.awt.Color(204, 204, 204));
        addValor.setForeground(new java.awt.Color(51, 51, 51));
        addValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addValor.setBorder(null);
        addValor.setMargin(new java.awt.Insets(0, 20, 0, 0));
        addValor.setPreferredSize(new java.awt.Dimension(15, 25));
        addValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addValorActionPerformed(evt);
            }
        });

        adicionarAmostra.setBackground(new java.awt.Color(51, 51, 51));
        adicionarAmostra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adicionarAmostra.setForeground(new java.awt.Color(204, 204, 204));
        adicionarAmostra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        adicionarAmostra.setText("Adicionar");
        adicionarAmostra.setContentAreaFilled(false);
        adicionarAmostra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarAmostra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        adicionarAmostra.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        adicionarAmostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAmostraActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Adicionar novo dado:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel8.setPreferredSize(new java.awt.Dimension(114, 30));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabela);
        DecimalFormat df = new DecimalFormat("##.#");

        removerLinha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        removerLinha.setForeground(new java.awt.Color(204, 204, 204));
        removerLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        removerLinha.setText("Remover linha ");
        removerLinha.setContentAreaFilled(false);
        removerLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removerLinha.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        removerLinha.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        removerLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerLinhaActionPerformed(evt);
            }
        });

        apagarTudo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        apagarTudo.setForeground(new java.awt.Color(204, 204, 204));
        apagarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        apagarTudo.setText("Apagar Tudo");
        apagarTudo.setContentAreaFilled(false);
        apagarTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apagarTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        apagarTudo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        apagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarTudoActionPerformed(evt);
            }
        });

        amostraTotal.setEditable(false);
        amostraTotal.setBackground(new java.awt.Color(204, 204, 204));
        amostraTotal.setForeground(new java.awt.Color(51, 51, 51));
        amostraTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amostraTotal.setBorder(null);
        amostraTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amostraTotalActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Linhas:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel7.setPreferredSize(new java.awt.Dimension(114, 30));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Coluna Desejada:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        delimitador.setBackground(new java.awt.Color(204, 204, 204));
        delimitador.setForeground(new java.awt.Color(51, 51, 51));
        delimitador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        delimitador.setText(";");
        delimitador.setBorder(null);
        delimitador.setPreferredSize(new java.awt.Dimension(15, 25));
        delimitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delimitadorActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delimitador:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        colunaDesejada.setBackground(new java.awt.Color(204, 204, 204));
        colunaDesejada.setForeground(new java.awt.Color(51, 51, 51));
        colunaDesejada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colunaDesejada.setText("1");
        colunaDesejada.setBorder(null);
        colunaDesejada.setPreferredSize(new java.awt.Dimension(15, 25));
        colunaDesejada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colunaDesejadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(labelArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(delimitador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(colunaDesejada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addValor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adicionarAmostra, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(arquivoLoc)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amostraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apagarTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arquivoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delimitador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionarAmostra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colunaDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerLinha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apagarTudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amostraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(280, 280, 280)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botaoResultados.setBackground(new java.awt.Color(51, 51, 51));
        botaoResultados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoResultados.setForeground(new java.awt.Color(204, 204, 204));
        botaoResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        botaoResultados.setText("Ver gráficos");
        botaoResultados.setContentAreaFilled(false);
        botaoResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoResultados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        botaoResultados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        botaoResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(botaoResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        jButton2.setText("Sobre");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/botao2.2.png"))); // NOI18N
        jButton3.setText("Ajuda");
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/Botao1.1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/logo interface.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File arquivo;

    private void mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediaActionPerformed

    double mediaInt;
    String mediaFinal;
    int total;
    double v[];
    int f[];

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed

        try {
            double valores[] = new double[tabela.getRowCount()];
            int colunaEscolhida = Integer.parseInt(colunaDesejada.getText());
            int colunaEscolhida1 = colunaEscolhida - 1;

            //Criar vetor com os valores da JTable
            for (int i = 0; i < valores.length; i++) {
                valores[i] = Double.parseDouble(tabela.getValueAt(i, colunaEscolhida1).toString());

            }

            //Calcular media
            mediaInt = calculos.getMedia(valores);
            mediaFinal = String.valueOf(mediaInt);                   //Media String

            //Ordenar vetor
            double aux;
            for (int i = 0; i < valores.length; i++) {
                for (int j = i + 1; j < valores.length; j++) {
                    if (valores[j] < valores[i]) {
                        aux = valores[i];
                        valores[i] = valores[j];
                        valores[j] = aux;
                    }
                }
            }

            //Calcular mediana
            double medianaD = calculos.getMediana(valores);
            String medianaString = String.valueOf(medianaD);                //Mediana String

            //Calcular Moda
            double modaD = calculos.getModa(valores);
            String modaString = String.valueOf(modaD);                      //Moda String

            //Calcular Variancia
            double varianciaD = calculos.getVariancia(valores);
            String varianciaString = String.valueOf(varianciaD);            //Variancia String

            //Calcular Desvio Padrão 
            double desvioPadraoD = calculos.getDesvioPadrao(valores);
            String desvioPadraoString = String.valueOf(desvioPadraoD);     //Desvio Padrao String

            //Calcular Coeficiente de Variação
            double coeficienteDeVariacaoD = calculos.getCoeficienteVariacao(valores);
            String coeficienteDeVariacaoString = String.valueOf(coeficienteDeVariacaoD);     //Desvio Padrao String

            DecimalFormat df = new DecimalFormat("##.#");

            //Definir caixas de texto na interface
            media.setText(df.format(mediaInt));
            mediana.setText(df.format(medianaD));
            moda.setText(df.format(modaD));
            variancia.setText(df.format(varianciaD));
            desvioPadrao.setText(df.format(desvioPadraoD));
            coeficienteDeVariacao.setText(df.format(coeficienteDeVariacaoD));
            botaoResultados.setEnabled(true);

            //Infos dos gráficos
            v = new double[valores.length];
            f = new int[valores.length];
            int j = 0;
            double ant = valores[0];
            int cont = 0;
            for (int i = 0; i < valores.length; i++) {
                if (ant == valores[i]) {
                    cont++;
                } else {
                    ant = valores[i];
                    j++;
                    cont = 1;
                }
                f[j] = cont;
                v[j] = valores[i];
            }

    }
    catch (NumberFormatException e

    
        ) {
            JOptionPane.showMessageDialog(this, "Coluna Inválida", "ERRO!", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medianaActionPerformed

    private void modaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modaActionPerformed

    private void varianciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varianciaActionPerformed

    private void desvioPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desvioPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desvioPadraoActionPerformed


    private void botaoResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResultadosActionPerformed
        TelaResultados Jframe = new TelaResultados();
        Jframe.setVisible(true);

        int colunaEscolhida = Integer.parseInt(colunaDesejada.getText());
        int colunaEscolhida1 = colunaEscolhida - 1;
        String titulo = tabela.getColumnName(colunaEscolhida1);
        
        
        try {
// poligono de frequencia
//Instância da classe apropriada do JFreeChart
            JFreeChart chart1 = ChartFactory.createXYLineChart(
                    "Grafico " + titulo,
                    tabela.getColumnName(colunaEscolhida1),
                    "Frequência",
                    dataset(),
                    PlotOrientation.VERTICAL,
                    true,
                    true,
                    false            
            ); 
            
            
//Algumas customizações (cores) 
            chart1.setBackgroundPaint(Color.white);
            XYPlot plot = chart1.getXYPlot();
            plot.setOutlinePaint(Color.white);
            plot.setBackgroundPaint(Color.white);
            plot.setDomainGridlinePaint(Color.gray);
            plot.setRangeGridlinePaint(Color.DARK_GRAY); 
                    
            
            
//Configuração dos eixos e escalas
            NumberAxis axis = (NumberAxis) plot.getDomainAxis();
            axis.setTickUnit(new NumberTickUnit(40));
            
//Criação do painel do gráfico e inserção no painel (jPainel5) da janela
            ChartPanel chartPanel = new ChartPanel(chart1);
            chartPanel.setPreferredSize(TelaResultados.painelGrafico1.getSize());
            TelaResultados.painelGrafico1.add(chartPanel, java.awt.BorderLayout.CENTER);
            this.getContentPane().validate();
            this.getContentPane().repaint();
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
try{
            // Histograma
            JFreeChart chart2 = ChartFactory.createHistogram(
                    "Grafico " + titulo, 
                    tabela.getColumnName(colunaEscolhida1), 
                    "Frequência",
                    dataset(), 
                    PlotOrientation.VERTICAL, 
                    false,
                    true,
                    false
            );
           
//Cizacustomizacoes 
           chart2.setBackgroundPaint(Color.white);
            XYPlot plot2 = chart2.getXYPlot();
            plot2.setOutlinePaint(Color.white);
            plot2.setBackgroundPaint(Color.white);
            plot2.setDomainGridlinePaint(Color.gray);
            plot2.setRangeGridlinePaint(Color.DARK_GRAY);  
            
            
//Configuração dos eixos e escalas
            NumberAxis axis = (NumberAxis) plot2.getDomainAxis();
            axis.setTickUnit(new NumberTickUnit(40));
            
            
            
//Criação do painel do gráfico e inserção no painel 
            ChartPanel chartPanel1 = new ChartPanel(chart2);
            chartPanel1.setPreferredSize(TelaResultados.painelGrafico2.getSize());
            TelaResultados.painelGrafico2.add(chartPanel1, java.awt.BorderLayout.CENTER);
            this.getContentPane().validate();
            this.getContentPane().repaint();
            
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoResultadosActionPerformed

    private XYSeriesCollection dataset() {
        
        int colunaEscolhida = Integer.parseInt(colunaDesejada.getText());
        int colunaEscolhida1 = colunaEscolhida - 1;
        String titulo = tabela.getColumnName(colunaEscolhida1);
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries serie = new XYSeries("variação " + titulo);
        
//Inserir o conjunto de valores, um para cada linha da tabela. Ex.:
        for(int i = 0; i<v.length;i++){
            if(v[i] != 0){
                serie.add(v[i],f[i]);
            }
        }
        
//Adicionar a série ao dataset e retornar
        dataset.addSeries(serie);
        return dataset;

    }

    private void delimitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delimitadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delimitadorActionPerformed


    private void removerLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerLinhaActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tabela.getModel();
        if (tabela.getSelectedRow() >= 0) {
            dtm.removeRow(tabela.getSelectedRow());
            tabela.setModel(dtm);
            total = tabela.getRowCount();
            amostraTotal.setText(String.valueOf(total));
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }


    }//GEN-LAST:event_removerLinhaActionPerformed

    private void colunaDesejadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colunaDesejadaActionPerformed

    }//GEN-LAST:event_colunaDesejadaActionPerformed

    private void apagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarTudoActionPerformed
        ((DefaultTableModel) tabela.getModel()).setRowCount(0);
        media.setText("");
        mediana.setText("");
        moda.setText("");
        variancia.setText("");
        desvioPadrao.setText("");
        coeficienteDeVariacao.setText("");
        amostraTotal.setText("");
        ((DefaultTableModel) tabela.getModel()).setColumnCount(0);
        arquivoLoc.setText("");
        adicionarAmostra.setEnabled(true);
        addValor.setEnabled(true);
    }//GEN-LAST:event_apagarTudoActionPerformed

    private void coeficienteDeVariacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteDeVariacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteDeVariacaoActionPerformed

    private void addValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addValorActionPerformed


    private void adicionarAmostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAmostraActionPerformed
        try {

            if (addValor.getText().equals("")) {
                throw new Exception("Forneça algum dado!");
            }
            String valor = addValor.getText().replace(',', '.');
            String lin[] = {valor};
            if (((DefaultTableModel) tabela.getModel()).getColumnCount() == 0) {
                ((DefaultTableModel) tabela.getModel()).addColumn("Amostra");
            }
            ((DefaultTableModel) tabela.getModel()).addRow(lin);
            total = tabela.getRowCount();
            botaoCalcular.setEnabled(true);
            colunaDesejada.setEditable(true);
            amostraTotal.setText(String.valueOf(total));
            addValor.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_adicionarAmostraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int retorno = fileChooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            arquivo = fileChooser.getSelectedFile();
            arquivoLoc.setText(arquivo.getAbsolutePath());

        } else {
            arquivo = null;
            arquivoLoc.setText("");
        }

        try {
            String delimitadorStr = delimitador.getText();

            //Abrir o arquivo
            BufferedReader br;
            br = new BufferedReader(new FileReader(arquivo));

            //Definir header da tabela
            String linha = br.readLine();
            StringTokenizer tokens = new StringTokenizer(linha, delimitadorStr);
            String header[] = new String[tokens.countTokens()];
            for (int i = 0; i < header.length; i++) {
                header[i] = tokens.nextToken();
            }
            DefaultTableModel modelo = new DefaultTableModel(header, 0);

            //Adicionar o resto das linhas
            DecimalFormat df = new DecimalFormat("##.#");

            linha = br.readLine();
            while (linha != null) {
                tokens = new StringTokenizer(linha, delimitadorStr);
                String row[] = new String[tokens.countTokens()];
                for (int i = 0; i < row.length; i++) {
                    row[i] = tokens.nextToken().replace(',', '.');
                }
                modelo.addRow(row);
                linha = br.readLine();
            }
            tabela.setModel(modelo);

            //Total de linhas
            int Total = tabela.getRowCount();
            String totalAmostra = String.valueOf(Total);
            amostraTotal.setText(totalAmostra);

            //Ativar escolher Coluna e botao Calcular
            colunaDesejada.setEditable(true);
            botaoCalcular.setEnabled(true);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.LIGHT_GRAY);

        for (int i = 0; i < tabela.getModel().getColumnCount(); i++) {
            tabela.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        adicionarAmostra.setEnabled(false);
        addValor.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void amostraTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amostraTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amostraTotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        telaSobre frame = new telaSobre();

        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaAjuda frame = new TelaAjuda();
        frame.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3AncestorAdded

    public static void main(String args[]) {

        Splash splash = new Splash();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interface().setVisible(true);
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addValor;
    private javax.swing.JButton adicionarAmostra;
    private javax.swing.JTextField amostraTotal;
    private javax.swing.JButton apagarTudo;
    private javax.swing.JTextField arquivoLoc;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoResultados;
    private javax.swing.JTextField coeficienteDeVariacao;
    private javax.swing.JTextField colunaDesejada;
    private javax.swing.JTextField delimitador;
    private javax.swing.JTextField desvioPadrao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelArquivo;
    private javax.swing.JTextField media;
    private javax.swing.JLabel mediaLabel;
    private javax.swing.JTextField mediana;
    private javax.swing.JLabel medianaLabel;
    private javax.swing.JLabel medianaLabel1;
    private javax.swing.JLabel medianaLabel2;
    private javax.swing.JLabel medianaLabel3;
    private javax.swing.JLabel medianaLabel4;
    private javax.swing.JTextField moda;
    private javax.swing.JButton removerLinha;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField variancia;
    // End of variables declaration//GEN-END:variables

}
